### ISSUE TITLE
字体字号以及宋体字不能加粗问题

### ISSUE THREAD

**Issue by 9527567** [paralevi/QDUthesis#3]
警告中有两个问题，一是中文字号未能正确的匹配pt，编译器默认选择就近的大小代替，可在导言中加入\usepackage{anyfontsize}解决。二是对宋体，仿宋使用\textbf{}无法生效产生的警告，封面个人信息表格中的\textbf{}建议删除。

**Comment by paralevi** [comment]
收到，感谢。有空时我跟进一下。

**Comment by 9527567** [comment]
感谢回复！
