### ISSUE TITLE
TexLive2023在Windows11系统下找不到FZXiaoBiaoSong-B05S字体

### ISSUE THREAD

**Issue by Khalas-light** [paralevi/QDUthesis#4]
可以把 QDUBachelor.cls 文件中的 FZXiaoBiaoSong-B05S 改为 FZXiaoBiaoSong-B05S.ttf

**Comment by paralevi** [comment]
您好，才看到。我之前在 Linux 环境中编译，没有遇到过这个问题。感谢反馈。
